server:
  port: 8080

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    generate-ddl: false
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/./data/h2/testdb
#      jdbc-url: jdbc:h2:./data/h2/testdb #./ Project root
      driver-class-name: org.h2.Driver
      username: sa
      password:
#    url: jdbc:h2:./data/h2/testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

#  sql:
#    init:
#      mode:
#      schema-locations: classpath:h2/schema.sql



